---
- name: Prepare hosts for OpenShift
  hosts: opnodes
  become: true
  remote_user: root
  
  tasks:
  - name: install basic packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
  - name: prep for quick install
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - gcc 
      - python-virtualenv
  - name: yum update
    shell: "yum update -y"
#  - name: install openshift atomic
#    yum:
#      name: atomic-openshift-utils
  
  - name: install docker
    yum:
      name: docker
  - name: insert trust for docker config
    lineinfile:
      path: /etc/sysconfig/docker
      regexp: '^OPTIONS'
      line: "OPTIONS='--selinux-enabled --log-driver=journald --signature-verification=false --insecure-registry 172.30.0.0/16'"


  - name: Enable service Docker
    service:
      name: docker
      enabled: yes

  - name: Start service docker, if not started
    service:
      name: docker
      state: started

  - name: set docker storage for option 3
    shell:  docker-storage-setup
    shell:  service docker restart
  
